# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy JSON files for data

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13.5
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: python -m pip install -r ./requirements.txt
      - name: Cache requests
        uses: actions/cache@v4
        with:
          path: tba_cache.sqlite
          key: ${{ runner.os }}-tbacache
          restore-keys: |
            ${{ runner.os }}-tbacache
      - name: Run Build.py
        run: python ./build.py
        env:
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
